import re
import os
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://secure.uat.pcinsurance.ca/")
    page.get_by_role("textbox", name="Email Address").click()
    page.get_by_role("textbox", name="Email Address").fill(os.getenv("MY_KEY"))
    page.get_by_role("textbox", name="Email Address").press("Tab")
    page.get_by_role("textbox", name="Password").fill(os.getenv("MY_VALUE"))
    page.get_by_test_id("submit").click()
    page.locator("div").filter(has_text=re.compile(r"^2014 HYUNDAIGENESIS 2\.0T 2DRPolicy number: 501004816Policy detailsPink Slip$")).get_by_test_id("driver-policy--0").click()
    page.get_by_test_id("nav").click()
    page.get_by_test_id("policy-summary").click()
    page.get_by_test_id("hab-policy--0").click()
    page.get_by_test_id("nav").click()
    page.get_by_text("Make a Request Arrow Icon").click()
    page.get_by_test_id("get-a-quote").click()
    page.wait_for_timeout(2000)
    #page.get_by_role("button", name="Continue").click()
    page.wait_for_timeout(2000)
    page.locator("label").filter(has_text="Other").click()
    page.get_by_test_id("start-request").click()
    page.get_by_role("textbox", name="How can we help you today?").click()
    page.get_by_role("textbox", name="How can we help you today?").fill("abc")
    page.get_by_test_id("manage").click()
    page.get_by_test_id("Save").click()
    page.get_by_role("link", name="Resume").click()
    page.get_by_test_id("submit").click()
    page.get_by_role("link", name="Account Summary").click()
    page.get_by_test_id("make-request").click()
    page.get_by_test_id("make-a-change").click()
    page.get_by_role("button", name="Continue").click()
    page.locator("label").filter(has_text="Cancel my Policy").click()
    page.get_by_test_id("start-request").click()
    page.get_by_test_id("continue").click()
    page.locator("label").filter(has_text="Other").click()
    page.get_by_role("textbox", name="What is the name of the").click()
    page.get_by_role("textbox", name="What is the name of the").fill("nupan")
    page.get_by_test_id("28").click()
    page.get_by_test_id("continue").click()
    page.get_by_text("DODGE/RAM DART GT 4DR").click()
    page.locator("label").filter(has_text="Other").click()
    page.get_by_role("textbox", name="Please provide details.").click()
    page.get_by_role("textbox", name="Please provide details.").fill("xyz")
    page.locator("label").filter(has_text="No").click()
    page.get_by_role("textbox", name="Postal code").click()
    page.get_by_role("textbox", name="Postal code").fill("n3w0h5")
    page.get_by_label("Street Name").select_option("BASSWOOD CRES")
    page.get_by_role("textbox", name="Street Number").click()
    page.get_by_role("textbox", name="Street Number").fill("9")
    page.get_by_test_id("continue").click()
    page.get_by_text("I, nupan, have read and").click()
    page.get_by_test_id("continue").click()
    page.locator("label").filter(has_text="Text Message").click()
    page.get_by_role("textbox", name="Phone Number").click()
    page.get_by_role("textbox", name="Phone Number").fill("3456789090")
    page.get_by_test_id("submit").click()
    page.get_by_test_id("make-request").click()
    page.get_by_test_id("ask-a-question").click()
    page.get_by_role("button", name="Continue").click()
    page.locator("label").filter(has_text="Other").click()
    page.get_by_test_id("start-request").click()
    page.get_by_text("HYUNDAI GENESIS 2.0T 2DR").click()
    page.get_by_role("textbox", name="How can we help you today?").click()
    page.get_by_role("textbox", name="How can we help you today?").fill("tyu")
    page.get_by_test_id("manage").click()
    page.get_by_role("button", name="Delete and restart").click()
    page.get_by_role("button", name="Restart", exact=True).click()
    with page.expect_popup() as page1_info:
        page.get_by_test_id("download-view-pink-slips").click()
    page1 = page1_info.value
    page1.close()
    page.get_by_test_id("nav").click()
    page.get_by_test_id("previous-request").click()
    page.get_by_test_id("nav").click()
    page.get_by_test_id("profile").click()
    page.get_by_test_id("nav").click()
    page.get_by_test_id("claims").click()
    page.get_by_test_id("nav").click()
    page.get_by_test_id("help").click()
    page.get_by_role("link", name="I want to print my Pink Slips").click()
    page.get_by_test_id("nav").click()
    page.get_by_test_id("contact").click()
    page.get_by_test_id("nav").click()
    page.get_by_test_id("disclosures").click()
    with page.expect_popup() as page2_info:
        page.get_by_text("Information IconTerms &").click()
    page2 = page2_info.value
    page2.close()
    page.get_by_test_id("nav").click()
    page.get_by_test_id("logout").click()
    page.get_by_role("link", name="Go Home").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
